### ISSUE TITLE
Instructions for Dashboard

### ISSUE THREAD

**Issue by suvarna-m** [UBC-MDS/DSCI_532_Group102_No_Suicide_Squad#20]
- Write up instructions on how to use this dashboard on the main page.

**Comment by suvarna-m** [comment]
Update: added instructions for each plot and on main page. Need to modify code so that the 'main page' text does not appear on _all_ tabs.

**Comment by annychih** [comment]
Thanks for the text, Suvarna! This issue is now solved.
