### ISSUE TITLE
Tab 1 Y-axis Ranges

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_532_Group102_No_Suicide_Squad#38]
Hi Manuel, 

Could you please change the y-axis ranges for the line charts on Tab 1 so that they all start from 0 and have the same max value?

Thank you!

Anny

**Comment by annychih** [comment]
One exception to this: Plot 1c can't have the same max value as the rest of the charts because the suicide rate fluctuates too much by country (but you already knew that ;) )

**Comment by suvarna-m** [comment]
Thanks Anny and Manuel! This issue has now been resolved.
