### ISSUE TITLE
Refactor code: change dropdowns to use dictionary inside list comprehension

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_532_Group102_No_Suicide_Squad#47]

**Comment by annychih** [comment]
Suvarna will do the dropdowns Region and Country dropdowns
Anny will do the dropdowns for Demographics for Tab 1 and Country for Tab 2

**Comment by annychih** [comment]
Correction: 
Suvarna will do the dropdowns in Tab 1
Anny will do the dropdown in Tab 2

**Comment by annychih** [comment]
Country dropdown in Tab 2 has now been done. It works! woot woot

**Comment by suvarna-m** [comment]
Region and Country dropdowns in Tab 1 also done!
