### ISSUE TITLE
In-class feedback

### ISSUE THREAD

**Issue by reikookamoto** [UBC-MDS/DSCI_532_Group102_No_Suicide_Squad#61]
Improvements:
- Defaut tab settings
- Different colour scheme for the line plot? Difficult to pick out worldwide average trend (yellow on white)
- Certain regions don't appear on second line plot 
- Link to which countries make up which (sub)regions
- You have to scroll a lot 
- Have it filtered through step by step
- Have a feature that allows you to filter by gender (as opposed to picking a gender and age group)
- 'Suicide rate by demographic groups' - slightly messy and difficult to read the lines

Positive notes:
- Socially conscious dashboard description!
- Good consistency across different plots

**Comment by annychih** [comment]
All feedback from Lab 3 have been summarized here: https://github.com/UBC-MDS/DSCI_532_Group102_No_Suicide_Squad/issues/64
