### ISSUE TITLE
Feedback from lab session on milestone2 deployment

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_532_Group102_No_Suicide_Squad#62]
- By continent: Use opacity(?) to make declutter the numbers
- By region within continent: Where there is no data, just write a disclaimer
- Suicide rate by demographic groups: 
    - make it bigger to make it less cluttered
    - filter for different lines
    - maybe delete all the text and name the chart above as "country and demographics" so that the filter clearly applies to both charts
- Scale the width of plots to match width of text

**Comment by annychih** [comment]
All feedback from Lab 3 have been summarized here: https://github.com/UBC-MDS/DSCI_532_Group102_No_Suicide_Squad/issues/64
