### ISSUE TITLE
Feedback: Too many lines in Suicide Rate by Demographic Groups graph

### ISSUE THREAD

**Issue by clsu22** [UBC-MDS/DSCI_532_Group102_No_Suicide_Squad#63]
Too many lines in Suicide Rate by Demographic Groups graph. It's hard for comparison and even for getting insights into which Demographic Groups the users are interested in. Two options may be helpful:
1. use `facet` to make subplots 
2. make a wider division of age and sex

**Comment by annychih** [comment]
All feedback from Lab 3 have been summarized here: https://github.com/UBC-MDS/DSCI_532_Group102_No_Suicide_Squad/issues/64
